graph LR;

	StateStore;
	Dispatcher((Dispatcher));
	Scheduler;
	Applications((Application Components));

	StateStore -->|/state| Dispatcher
    Dispatcher -->|/state/a| StatefulAppA
	Dispatcher -->|/state/*| Scheduler
    Dispatcher -->|/state/b| StatefulAppB
	Scheduler --> Applications
    SensorA --> StateStore
    SensorB --> StateStore
