graph LR;

	StateStore;
	Dispatcher((Dispatcher));
	Scheduler;
	Discovery((Discovery));
	Applications((Application Components));

	StateStore --> Dispatcher
	Dispatcher --> Scheduler
    Dispatcher --> Applications
	Scheduler --> Applications
	Applications --> Discovery
    Discovery --> Applications
