graph LR;

	StateStore;
	Dispatcher;
	Scheduler;
	Discovery;
	Applications((Application Components));

	StateStore --> Dispatcher
	Dispatcher --> Scheduler
	Scheduler --> Applications
	Applications --> Discovery
