graph LR;

	StateStore;
	Dispatcher((Dispatcher));
	Scheduler;
    HostLoadSensor((Sensor));

	StateStore --> Dispatcher
	Dispatcher --> Scheduler
    Scheduler --> HostLoadSensor 
    HostLoadSensor --> StateStore 
